apt_redmine_packages:
  - mysql-server
  - mysql-client
  - python-pymysql
  - python-mysqldb
  - git
  - ruby-full
  - build-essential
  - libmysqlclient-dev
  - imagemagick
  - libmagickwand-dev

  
app_repo: "https://github.com/redmine/redmine.git"
app_home: /opt/redmine
app_version: 4.0-stable
